on:
  workflow_dispatch:

jobs:
  github-example-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: olegtarasov/get-tag@v2.1.2
        id: tagName
      - name: Some ot
        run: echo ${{ steps.tagName.outputs.tag }}
      - name: Yet another step
        run: |
          echo $GIT_TAG_NAME
